insert into products(product_id,name,product,color,size,season,price) values('1','Kathrine','Skirt','Navy','XS','AW21','69.9');
insert into products(product_id,name,product,color,size,season,price) values('2','Kathrine','Skirt','Navy','S','AW21','69.9');
insert into products(product_id,name,product,color,size,season,price) values('3','Kathrine','Skirt','Navy','M','AW21','69.9');
insert into products(product_id,name,product,color,size,season,price) values('4','Kathrine','Skirt','Navy','L','AW21','69.9');
insert into products(product_id,name,product,color,size,season,price) values('5','Kathrine','Skirt','Navy','XL','AW21','69.9');
insert into products(product_id,name,product,color,size,season,price) values('6','Kathrine','Skirt','Forest Green','XS','AW21','69.9');
insert into products(product_id,name,product,color,size,season,price) values('7','Kathrine','Skirt','Forest Green','S','AW21','69.9');
insert into products(product_id,name,product,color,size,season,price) values('8','Kathrine','Skirt','Forest Green','M','AW21','69.9');
insert into products(product_id,name,product,color,size,season,price) values('9','Kathrine','Skirt','Forest Green','L','AW21','69.9');
insert into products(product_id,name,product,color,size,season,price) values('10','Kathrine','Skirt','Forest Green','XL','AW21','69.9');
insert into products(product_id,name,product,color,size,season,price) values('11','Poppy','Dress','Orange','XS','AW21','99.9');
insert into products(product_id,name,product,color,size,season,price) values('12','Poppy','Dress','Orange','S','AW21','99.9');
insert into products(product_id,name,product,color,size,season,price) values('13','Poppy','Dress','Orange','M','AW21','99.9');
insert into products(product_id,name,product,color,size,season,price) values('14','Poppy','Dress','Orange','L','AW21','99.9');
insert into products(product_id,name,product,color,size,season,price) values('15','Poppy','Dress','Orange','XL','AW21','99.9');
insert into products(product_id,name,product,color,size,season,price) values('16','Poppy','Dress','Floral','XS','AW21','99.9');
insert into products(product_id,name,product,color,size,season,price) values('17','Poppy','Dress','Floral','S','AW21','99.9');
insert into products(product_id,name,product,color,size,season,price) values('18','Poppy','Dress','Floral','M','AW21','99.9');
insert into products(product_id,name,product,color,size,season,price) values('19','Poppy','Dress','Floral','L','AW21','99.9');
insert into products(product_id,name,product,color,size,season,price) values('20','Poppy','Dress','Floral','XL','AW21','99.9');
insert into products(product_id,name,product,color,size,season,price) values('21','Greta','Jumpsuit','Beige','XS','AW21','129.9');
insert into products(product_id,name,product,color,size,season,price) values('22','Greta','Jumpsuit','Beige','S','AW21','129.9');
insert into products(product_id,name,product,color,size,season,price) values('23','Greta','Jumpsuit','Beige','M','AW21','129.9');
insert into products(product_id,name,product,color,size,season,price) values('24','Greta','Jumpsuit','Beige','L','AW21','129.9');
insert into products(product_id,name,product,color,size,season,price) values('25','Greta','Jumpsuit','Beige','XL','AW21','129.9');
insert into products(product_id,name,product,color,size,season,price) values('26','Pamela','Shirt','Rose','XS','AW21','79.9');
insert into products(product_id,name,product,color,size,season,price) values('27','Pamela','Shirt','Rose','S','AW21','79.9');
insert into products(product_id,name,product,color,size,season,price) values('28','Pamela','Shirt','Rose','M','AW21','79.9');
insert into products(product_id,name,product,color,size,season,price) values('29','Pamela','Shirt','Rose','L','AW21','79.9');
insert into products(product_id,name,product,color,size,season,price) values('30','Pamela','Shirt','Rose','XL','AW21','79.9');
insert into products(product_id,name,product,color,size,season,price) values('26','Pamela','Shirt','Jade','XS','AW21','79.9');
insert into products(product_id,name,product,color,size,season,price) values('27','Pamela','Shirt','Jade','S','AW21','79.9');
insert into products(product_id,name,product,color,size,season,price) values('28','Pamela','Shirt','Jade','M','AW21','79.9');
insert into products(product_id,name,product,color,size,season,price) values('29','Pamela','Shirt','Jade','L','AW21','79.9');
insert into products(product_id,name,product,color,size,season,price) values('30','Pamela','Shirt','Jade','XL','AW21','79.9');
insert into products(product_id,name,product,color,size,season,price) values('31','Pamela','Shirt','Jade','XXL','AW21','79.9');
